#!/usr/bin/env python3
"""Concept-page wiki generator (issue #148).

Emits an Obsidian-readable wiki slice - one page per top-N stable taxonomy
concept plus a `concept-pages.md` Map of Content - into
`<out>/_wiki/concept-pages` (or an explicit `--out`). Companion to
`scripts/wiki_atlas.py` (issue #105): same house style (frontmatter stamps,
wikilink discipline, TODO-PROSE slots), different data source and a
different generator, per the one-generator-not-a-framework discipline from
issue #95. The default output directory is deliberately its own namespace,
distinct from `wiki_atlas.py`'s `concepts/` folder (issue #150 P1) - the two
generators' pages must never share a directory, because `write_pages`
refuses to overwrite a page stamped by a foreign generator rather than
silently clobbering it, and only prunes stale pages this same generator
wrote in a prior run.

Read-only against the corpus: `taxonomy.json` (canonical labels/aliases) +
per-video `concepts.json` (concept membership) + `meta.json` (video
identity) + `mindmap.md` (timestamps for evidence links). No LLM calls, no
embeddings, no databases - plain Python over JSON/Markdown already on disk
(issue #148 guardrail 2). Pages are mechanical skeletons with TODO-PROSE
slots; an executing agent fills the prose in a later, separately gated step
(guardrail 3).

Standalone by design: this does NOT add a `video_intel.py` subcommand, so it
sidesteps the `CONFIG_BACKUP_COMMANDS` classification question entirely -
see the PR body for the full reasoning. It never touches `config.yaml` or
any file inside the corpus other than the read-only artifacts named above;
its only write surface is the `--out` directory.
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from wiki_atlas import slugify

from timestamp_utils import TIMESTAMP_TOKEN_PATTERN, parse_time_to_seconds, timestamped_url

log = logging.getLogger(__name__)

GENERATOR_NAME = "wiki_concepts.py"
GENERATOR_VERSION = "1"

DEFAULT_TOP_N = 20
MIN_STABLE_CHANNELS = 3
MIN_AS_MENTIONED_FALLBACK_LEN = 4

CONCEPTS_SUFFIX = ".concepts.json"
META_SUFFIX = ".meta.json"
MINDMAP_SUFFIX = ".mindmap.md"

# Basename of the Map-of-Content page (issue #150 FIX1b). Distinct from the
# generic "index" so a bare `[[index]]` wikilink in an Obsidian vault that
# also holds wiki_atlas.py's own index.md is never ambiguous. Reserved in
# `_assign_slugs` so no concept can claim this filename for itself.
MOC_BASENAME = "concept-pages"

PROSE_TODO = "> [!todo] PROSE (agent)"
PROSE_INLINE = "(TODO-PROSE: one-line context)"

REGEN_NOTICE = (
    "Regenerated by rerunning the generator. A re-run REPLACES THE ENTIRE "
    "FILE, including any prose already filled into the `> [!todo] PROSE` "
    "blocks below - nothing on this page survives a regeneration."
)


# ---------------------------------------------------------------------------
# Domain model
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class VideoRecord:
    """One corpus video, identified the way the writer identified it on disk."""

    channel: str
    video_id: str
    title: str
    published: str  # ISO date string, "" if unknown
    video_url: str
    prefix: str
    mindmap_path: Path | None


@dataclass(frozen=True)
class Mention:
    """One (concept, video) membership fact, from that video's concepts.json."""

    video: VideoRecord
    concept_id: str
    preferred_label: str
    as_mentioned: str
    branch: str


@dataclass(frozen=True)
class MindmapEntry:
    """One bullet line parsed out of a mindmap.md, with its first timestamp."""

    heading: str
    subheading: str
    text: str
    seconds: int | None


# ---------------------------------------------------------------------------
# Corpus walk - never rebuilds artifact paths from parts (PR #136 guardrail)
# ---------------------------------------------------------------------------


def _is_channel_dir(path: Path) -> bool:
    return path.is_dir() and not path.name.startswith((".", "_"))


def artifact_prefix(concepts_path: Path) -> str:
    """The on-disk prefix for a concepts.json file (e.g. '2026-01-29-title')."""
    return concepts_path.name[: -len(CONCEPTS_SUFFIX)]


def sibling_artifacts(concepts_path: Path) -> dict[str, Path]:
    """Map of suffix (e.g. '.meta.json') -> path, from files actually present
    beside this concepts.json on disk.

    The prefix comes from the concepts.json filename the corpus walk already
    found, never rebuilt from title/date parts - the exact failure PR #136
    fixed (a checker that re-derives a writer's path independently, and
    drifts from it).

    Uses `iterdir()` + a literal `startswith` check rather than
    `Path.glob(f"{prefix}.*")` (issue #150 FIX5): a prefix containing glob
    metacharacters - `[`, `]`, `*`, `?` - is common (a bracketed video title
    like "talk [final]") and glob would silently interpret them as pattern
    syntax instead of literal characters, losing real siblings.
    """
    prefix = artifact_prefix(concepts_path)
    prefix_dot = f"{prefix}."
    out: dict[str, Path] = {}
    for sib in concepts_path.parent.iterdir():
        if sib.is_file() and sib.name.startswith(prefix_dot):
            out[sib.name[len(prefix) :]] = sib
    return out


# Tracks files skipped as unreadable/unparseable across one corpus walk
# (issue #150 FIX6). Reset at the start of `collect_corpus_videos` - the
# single entry point every walk (direct or via `build_pages`) goes through -
# so each run's count reflects that run, not a leaked prior one.
_SKIPPED_FILES: list[str] = []


def reset_skip_tracking() -> None:
    """Test hook / explicit reset: clear the skipped-file tracker."""
    _SKIPPED_FILES.clear()


def skipped_file_count() -> int:
    return len(_SKIPPED_FILES)


def _read_json_best_effort(path: Path) -> dict | None:
    """Best-effort JSON read; None when missing, unreadable, or unparseable.

    A simply-ABSENT file (e.g. no `taxonomy.json` yet, before `taxonomy-build`
    has run) is normal and not logged or counted - only a file that EXISTS
    but fails to read or parse is a genuine corruption signal worth
    surfacing (issue #150 FIX6).
    """
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        log.warning("skipping unreadable/unparseable JSON file %s: %s", path, exc)
        _SKIPPED_FILES.append(str(path))
        return None


def _read_text_best_effort(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        log.warning("skipping unreadable file %s: %s", path, exc)
        _SKIPPED_FILES.append(str(path))
        return None


def collect_corpus_videos(corpus: Path) -> list[tuple[VideoRecord, list[dict]]]:
    """Walk `<corpus>/<channel>/*.concepts.json`; return (video, concept-dicts).

    Skips `.`- and `_`-prefixed directories, mirroring the corpus walker
    convention (`_wiki`, `_briefings`, `_reports`, `_config-backups` are
    output folders, never channels).

    Resets the skipped-file tracker (issue #150 FIX6) - this is the single
    entry point every walk goes through, directly or via `build_pages`, so
    `skipped_file_count()` after a call reflects this run only.
    """
    reset_skip_tracking()
    records: list[tuple[VideoRecord, list[dict]]] = []
    if not corpus.is_dir():
        return records
    for channel_dir in sorted(p for p in corpus.iterdir() if _is_channel_dir(p)):
        for cpath in sorted(channel_dir.glob(f"*{CONCEPTS_SUFFIX}")):
            cdata = _read_json_best_effort(cpath)
            if not cdata:
                continue
            concepts = cdata.get("concepts") or []
            if not concepts:
                continue
            sibs = sibling_artifacts(cpath)
            meta = _read_json_best_effort(sibs[META_SUFFIX]) if META_SUFFIX in sibs else None
            meta = meta or {}
            prefix = artifact_prefix(cpath)
            video_id = meta.get("video_id") or cdata.get("video_id") or prefix
            title = meta.get("title") or prefix
            published = meta.get("published") or ""
            video_url = meta.get("video_url") or (f"https://www.youtube.com/watch?v={video_id}" if video_id else "")
            video = VideoRecord(
                channel=channel_dir.name,
                video_id=video_id,
                title=title,
                published=published,
                video_url=video_url,
                prefix=prefix,
                mindmap_path=sibs.get(MINDMAP_SUFFIX),
            )
            records.append((video, concepts))
    return records


def load_taxonomy(corpus: Path) -> dict[str, dict]:
    """Best-effort read of taxonomy.json's concept table; {} if missing/corrupt."""
    data = _read_json_best_effort(corpus / "taxonomy.json")
    if not data:
        return {}
    concepts = data.get("concepts")
    return concepts if isinstance(concepts, dict) else {}


# ---------------------------------------------------------------------------
# Concept membership + stability selection
# ---------------------------------------------------------------------------


def build_mentions(records: list[tuple[VideoRecord, list[dict]]]) -> dict[str, list[Mention]]:
    """Join concept -> videos via each video's own concepts.json, deduping a
    concept that (rarely) appears twice in one video's concept list."""
    by_concept: dict[str, list[Mention]] = {}
    for video, concepts in records:
        seen_this_video: set[str] = set()
        for c in concepts:
            cid = c.get("concept_id")
            if not cid or cid in seen_this_video:
                continue
            seen_this_video.add(cid)
            by_concept.setdefault(cid, []).append(
                Mention(
                    video=video,
                    concept_id=cid,
                    preferred_label=c.get("preferred_label") or cid,
                    as_mentioned=c.get("as_mentioned") or "",
                    branch=c.get("branch") or "",
                )
            )
    return by_concept


def canonical_channel_by_video(mentions: list[Mention]) -> dict[str, str]:
    """One canonical channel per video_id, chosen deterministically as the
    lexicographically smallest channel among all mentions of that video
    (issue #150 second review round, FIX10).

    Shared by every consumer that groups or counts by channel - stability
    selection (`select_stable_concepts`), the per-concept page
    (`_concept_page`), and the MOC (`_index`) - so a video mis-filed under
    two or more channel-folder names (a title-rotation duplicate not yet
    cleaned by `dedupe --apply`) is counted, selected, AND rendered under
    exactly ONE channel everywhere. Before this helper existed, selection
    deduped by video_id but rendering did not: a duplicated video inflated
    "N videos across M channels" on the concept page and the MOC, and the
    video itself was listed twice - once under each channel heading. Picking
    the smallest channel name (rather than, say, "first encountered") keeps
    the result independent of iteration/insertion order, so any caller gets
    the same answer regardless of which subset or ordering of mentions it
    holds.
    """
    canon: dict[str, str] = {}
    for m in mentions:
        vid = m.video.video_id
        if vid not in canon or m.video.channel < canon[vid]:
            canon[vid] = m.video.channel
    return canon


def select_stable_concepts(
    mentions_by_concept: dict[str, list[Mention]],
    top_n: int = DEFAULT_TOP_N,
    min_channels: int = MIN_STABLE_CHANNELS,
) -> list[str]:
    """Rank concepts by distinct-video count; keep only ones seen across
    `>= min_channels` distinct channels (one creator's pet vocabulary must
    not claim a page even at high count). Deterministic tie-break on
    concept_id so a rerun with unchanged inputs orders identically.

    Channel membership is deduped by video_id first (issue #150 FIX8b) via
    `canonical_channel_by_video` - a title-rotation duplicate not yet
    cleaned by `dedupe` can leave the same video_id filed under two
    channel-folder names, and counting each occurrence's own `channel`
    directly would let that corpus-housekeeping debt spoof cross-channel
    stability for what is really one video from one creator - exactly what
    this filter exists to prevent.
    """
    scored: list[tuple[str, int]] = []
    for cid, mentions in mentions_by_concept.items():
        channel_by_video = canonical_channel_by_video(mentions)
        channels = set(channel_by_video.values())
        if len(channels) < min_channels:
            continue
        video_count = len(channel_by_video)
        scored.append((cid, video_count))
    scored.sort(key=lambda t: (-t[1], t[0]))
    return [cid for cid, _ in scored[:top_n]]


def build_co_occurrence(records: list[tuple[VideoRecord, list[dict]]], selected_ids: set[str]) -> dict[str, Counter]:
    """concept_id -> Counter(other_concept_id -> shared-video count), scoped
    to the selected concept set only - the "Related concepts" cross-link
    source. Restricting to selected_ids means every link this produces
    points at a page that exists in this run (zero dead wikilinks).

    Deduped by video_id (issue #150 FIX8b): a title-rotation duplicate (same
    video_id, two concepts.json files under different prefixes/dates before
    `dedupe --apply` runs) must count as one shared video, not two - a bare
    per-record tally would inflate co-occurrence strength by corpus
    housekeeping debt rather than genuine cross-video evidence.
    """
    pair_videos: dict[tuple[str, str], set[str]] = {}
    for video, concepts in records:
        ids_in_video = sorted({c.get("concept_id") for c in concepts if c.get("concept_id") in selected_ids})
        for a in ids_in_video:
            for b in ids_in_video:
                if a != b:
                    pair_videos.setdefault((a, b), set()).add(video.video_id)
    co: dict[str, Counter] = {cid: Counter() for cid in selected_ids}
    for (a, b), video_ids in pair_videos.items():
        co[a][b] = len(video_ids)
    return co


# ---------------------------------------------------------------------------
# Mindmap timestamp parsing (mechanical; matches the mindmap-from-transcript
# prompt's heading / subheading / timestamped-bullet shape - see
# prompts/mindmap-from-transcript.md)
# ---------------------------------------------------------------------------

_HEADING_RE = re.compile(r"^##\s+(.+)$")
_SUBHEADING_RE = re.compile(r"^\*\s+\*\*(.+?)\*\*\s*$")
_BULLET_TIME_RE = re.compile(r"\(([\d:,\s]+)\)\s*$")
# Issue #195 (same class as chunk_transcript's boundary fix): the minute field
# is unbounded because rendered timestamps carry minutes past 59. The capped
# form was WORSE than a miss here - findall("100:18") matched "00:18" and
# anchored the citation 100 minutes early, violating this module's own
# never-fabricate-a-timestamp contract (invariant 4).
_TIME_TOKEN_RE = re.compile(TIMESTAMP_TOKEN_PATTERN)


def _whole_token_pattern(term: str) -> re.Pattern[str]:
    """Punctuation-aware whole-token match for `term` inside a larger string.

    Mirrors `video_intel.py`'s `_alias_boundary_pattern` (duplicated rather
    than imported: importing `video_intel` here would drag in its heavy
    transitive deps, which is the same reason `timestamped_url` and
    `parse_time_to_seconds` live in `timestamp_utils` - see issue #152).
    stdlib `\\b` only matches between a word and a non-word character, so it
    silently fails for terms that begin/end with punctuation; the boundary
    here treats any non-word character OR the string edges as a boundary.
    """
    return re.compile(r"(?:^|(?<=[^\w]))" + re.escape(term) + r"(?=$|[^\w])", flags=re.IGNORECASE)


def parse_mindmap_timestamps(text: str) -> list[MindmapEntry]:
    """Parse `## heading` / `* **subheading**` / `  - bullet (M:SS)` rows into
    a flat list carrying each bullet's first timestamp (seconds), or None
    when a bullet carries no parseable timestamp. Not a markdown library -
    the corpus's mindmap shape is stable and prompt-defined."""
    entries: list[MindmapEntry] = []
    heading = ""
    subheading = ""
    for raw_line in text.splitlines():
        line = raw_line.strip()
        h = _HEADING_RE.match(line)
        if h:
            heading = h.group(1).strip()
            subheading = ""
            continue
        s = _SUBHEADING_RE.match(line)
        if s:
            subheading = s.group(1).strip()
            continue
        if not line.startswith("-"):
            continue
        seconds = None
        m = _BULLET_TIME_RE.search(line)
        if m:
            tokens = _TIME_TOKEN_RE.findall(m.group(1))
            if tokens:
                try:
                    seconds = parse_time_to_seconds(tokens[0])
                except ValueError:
                    seconds = None
        bullet_text = _BULLET_TIME_RE.sub("", line).lstrip("-").strip()
        entries.append(MindmapEntry(heading=heading, subheading=subheading, text=bullet_text, seconds=seconds))
    return entries


def find_timestamp(entries: list[MindmapEntry], branch: str, as_mentioned: str) -> int | None:
    """Deterministic, mechanical lookup for the timestamp behind one concept
    mention: first try a subheading match on `branch`, then a heading match,
    then a whole-token match of `as_mentioned` inside any bullet's text. None
    when nothing matches - callers must not fabricate a timestamp; an
    un-anchored citation renders without `&t=` rather than with a wrong one.

    The `as_mentioned` fallback requires a punctuation-aware whole-token
    match, not a bare substring test (issue #150 FIX3): a short phrase like
    "AI" is a substring of ordinary words ("m-AI-ntain", "s-AI-d") and a
    naive `in` check would anchor the citation to an unrelated bullet. A
    minimum normalized length of 4 chars is required before the fallback
    may fire at all - below that, a wrong link is worse than no link.
    """
    branch_norm = branch.strip().lower()
    as_mentioned_norm = as_mentioned.strip().lower()
    if branch_norm:
        for e in entries:
            if e.seconds is not None and e.subheading.strip().lower() == branch_norm:
                return e.seconds
        for e in entries:
            if e.seconds is not None and e.heading.strip().lower() == branch_norm:
                return e.seconds
    if len(as_mentioned_norm) >= MIN_AS_MENTIONED_FALLBACK_LEN:
        pattern = _whole_token_pattern(as_mentioned_norm)
        for e in entries:
            if e.seconds is not None and pattern.search(e.text.strip().lower()):
                return e.seconds
    return None


def mention_link(m: Mention, entries_cache: dict[Path, list[MindmapEntry]]) -> str:
    """URL for one mention: `&t=<seconds>` when a timestamp can be located in
    the video's mindmap, else the plain video URL - never a fabricated time."""
    seconds = None
    if m.video.mindmap_path is not None:
        entries = entries_cache.get(m.video.mindmap_path)
        if entries is None:
            text = _read_text_best_effort(m.video.mindmap_path)
            entries = parse_mindmap_timestamps(text) if text is not None else []
            entries_cache[m.video.mindmap_path] = entries
        seconds = find_timestamp(entries, m.branch, m.as_mentioned)
    return timestamped_url(m.video.video_url, seconds)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _escape_md_table_cell(text: str) -> str:
    """Escape characters that break a Markdown table row or a `[text](url)`
    link (issue #150 FIX4): a video title or a concept's `as_mentioned` /
    `branch` phrase is creator-authored text that can contain a literal
    `|` (splits the table row) or `[`/`]` (breaks the link's text span).
    """
    return text.replace("|", "\\|").replace("[", "\\[").replace("]", "\\]")


def _concept_page(
    concept_id: str,
    mentions: list[Mention],
    taxonomy: dict[str, dict],
    co_occurrence: dict[str, Counter],
    slug_for: dict[str, str],
    entries_cache: dict[Path, list[MindmapEntry]],
    corpus: Path,
) -> str:
    tax_entry = taxonomy.get(concept_id, {})
    label = tax_entry.get("preferred_label") or mentions[0].preferred_label
    aliases = tax_entry.get("aliases") or []
    domain = tax_entry.get("domain") or ""
    # video_id-normalized (issue #150 FIX10): a video mis-filed under two
    # channel-folder names must be counted once and rendered under exactly
    # one channel heading below - see `canonical_channel_by_video`.
    channel_by_video = canonical_channel_by_video(mentions)
    video_ids = sorted(channel_by_video)
    channels = sorted(set(channel_by_video.values()))

    lines = [
        "---",
        "type: concept",
        f"concept_id: {concept_id}",
        f"generator: {GENERATOR_NAME}",
        f"generator_version: {GENERATOR_VERSION!r}",
        f"generated_from: {corpus.name}",
        f"videos: {len(video_ids)}",
        f"channels: {len(channels)}",
        "---",
        "",
        f"# {label}",
        "",
        f"> {REGEN_NOTICE}",
        "",
        PROSE_TODO,
        f"> Write 2-3 paragraphs on {label}: what it is, why it recurs across "
        "creators, and a judgment on where it is heading.",
        "",
    ]
    if domain:
        lines += [f"Domain: `{domain}`", ""]
    if aliases:
        lines += ["## Aliases", ""]
        lines += [f"- {a}" for a in sorted(aliases)]
        lines.append("")

    lines += [f"## Member videos ({len(video_ids)} across {len(channels)} channels)", ""]
    # Grouped by CANONICAL channel, not each mention's raw `m.video.channel`
    # (issue #150 FIX10): a video mis-filed under two channel-folder names
    # would otherwise land in both groups and be listed under both headings.
    # `seen_videos` below still guards within a group in case of duplicate
    # Mention rows for the same video_id.
    by_channel: dict[str, list[Mention]] = {}
    for m in mentions:
        by_channel.setdefault(channel_by_video[m.video.video_id], []).append(m)
    for channel in sorted(by_channel):
        lines += [f"### {channel}", "", "| Date | Video | As mentioned |", "|---|---|---|"]
        rows = sorted(by_channel[channel], key=lambda m: (m.video.published, m.video.title, m.video.video_id))
        seen_videos: set[str] = set()
        for m in rows:
            if m.video.video_id in seen_videos:
                continue
            seen_videos.add(m.video.video_id)
            link = mention_link(m, entries_cache)
            date = m.video.published or "(date unknown)"
            claim = m.as_mentioned or m.branch or "-"
            title_cell = _escape_md_table_cell(m.video.title)
            claim_cell = _escape_md_table_cell(claim)
            lines.append(f"| {date} | [{title_cell}]({link}) | {claim_cell} |")
        lines.append("")

    related = co_occurrence.get(concept_id, Counter())
    related_ranked = sorted(
        ((cid, n) for cid, n in related.items() if cid in slug_for and cid != concept_id),
        key=lambda t: (-t[1], t[0]),
    )
    if related_ranked:
        lines += ["## Related concepts", ""]
        for cid, n in related_ranked:
            other_label = taxonomy.get(cid, {}).get("preferred_label") or cid
            plural = "s" if n != 1 else ""
            lines.append(f"- [[{slug_for[cid]}]] ({other_label}) - shares {n} video{plural} - {PROSE_INLINE}")
        lines.append("")

    return "\n".join(lines)


def _index(
    selected_ids: list[str],
    mentions_by_concept: dict[str, list[Mention]],
    taxonomy: dict[str, dict],
    slug_for: dict[str, str],
    corpus: Path,
) -> str:
    lines = [
        "---",
        "type: index",
        f"generator: {GENERATOR_NAME}",
        f"generator_version: {GENERATOR_VERSION!r}",
        f"generated_from: {corpus.name}",
        f"pages: {len(selected_ids)}",
        "---",
        "",
        "# Concept Atlas",
        "",
        f"> {REGEN_NOTICE}",
        "",
        PROSE_TODO,
        "> Write the MOC intro: what this atlas is, how to wander it, one line of context per link below.",
        "",
        f"## Top {len(selected_ids)} stable concepts",
        "",
    ]
    for i, cid in enumerate(selected_ids, start=1):
        mentions = mentions_by_concept[cid]
        # video_id-normalized (issue #150 FIX10), same helper and same
        # policy as `_concept_page` and `select_stable_concepts` - the MOC
        # count must agree with the concept page's own header.
        channel_by_video = canonical_channel_by_video(mentions)
        video_ids = set(channel_by_video)
        channels = set(channel_by_video.values())
        label = taxonomy.get(cid, {}).get("preferred_label") or mentions[0].preferred_label
        lines.append(
            f"{i}. [[{slug_for[cid]}]] - {label} - {len(video_ids)} videos across "
            f"{len(channels)} channels - {PROSE_INLINE}"
        )
    lines.append("")
    return "\n".join(lines)


def _assign_slugs(selected_ids: list[str]) -> dict[str, str]:
    """Deterministic slug per concept_id, disambiguating collisions with a
    numeric suffix (mirrors wiki_atlas's collision handling) so one page
    never silently overwrites another.

    `MOC_BASENAME` is seeded into `used` (issue #150 FIX7) so a concept_id
    that happens to slugify to the MOC's own filename gets pushed to a "-2"
    suffix instead of silently colliding with the index page.
    """
    slug_for: dict[str, str] = {}
    used: set[str] = {MOC_BASENAME}
    for cid in selected_ids:
        base = slug = slugify(cid)
        n = 2
        while slug in used:
            slug = f"{base}-{n}"
            n += 1
        used.add(slug)
        slug_for[cid] = slug
    return slug_for


def build_pages(
    corpus: Path,
    top_n: int = DEFAULT_TOP_N,
    min_channels: int = MIN_STABLE_CHANNELS,
) -> dict[str, str]:
    """Pure(ish) top-level renderer: corpus directory -> {relative path: markdown}.

    The only filesystem interaction is reading; nothing is written here.
    """
    records = collect_corpus_videos(corpus)
    mentions_by_concept = build_mentions(records)
    selected_ids = select_stable_concepts(mentions_by_concept, top_n=top_n, min_channels=min_channels)
    taxonomy = load_taxonomy(corpus)
    co_occurrence = build_co_occurrence(records, set(selected_ids))
    slug_for = _assign_slugs(selected_ids)
    entries_cache: dict[Path, list[MindmapEntry]] = {}

    pages: dict[str, str] = {}
    for cid in selected_ids:
        pages[f"{slug_for[cid]}.md"] = _concept_page(
            cid, mentions_by_concept[cid], taxonomy, co_occurrence, slug_for, entries_cache, corpus
        )
    pages[f"{MOC_BASENAME}.md"] = _index(selected_ids, mentions_by_concept, taxonomy, slug_for, corpus)
    return pages


def _frontmatter_generator(text: str) -> str | None:
    """Best-effort read of the `generator:` value from a page's frontmatter
    block (issue #150 FIX1c). Returns None when there is no frontmatter, no
    `generator:` key, or an empty value - a foreign page that predates any
    generator stamp is treated the same as "no signal", never as "safe to
    overwrite" or "ours"."""
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    for line in text[3:end].splitlines():
        line = line.strip()
        if line.startswith("generator:"):
            value = line.split(":", 1)[1].strip()
            return value or None
    return None


def write_pages(pages: dict[str, str], out_dir: Path) -> None:
    """Write every page under out_dir; refuses to write anywhere else.

    Two namespace-collision guards (issue #150 FIX1), both scoped to
    `out_dir` only - this generator never looks outside its own `--out`:

    - **Fail-closed ownership (issue #150 second review round, FIX9).** An
      existing file is overwritten ONLY when its frontmatter's `generator:`
      value is EXACTLY `GENERATOR_NAME`. Every other state - no frontmatter,
      empty or malformed frontmatter, a foreign generator's stamp, or a
      file that cannot be read at all - aborts the whole run (nothing is
      written) rather than falling through to an overwrite. The prior
      revision only refused when it could positively identify a *different*
      generator's stamp; an unreadable file or missing/malformed
      frontmatter fell through that check and was silently overwritten -
      exactly the failure `_frontmatter_generator`'s own docstring warns
      against, and the vector by which a same-named hand-authored note
      would be destroyed by a routine rerun.
    - **Own-stale pruning.** After writing, files already in `out_dir` that
      this SAME generator wrote in a prior run but that are absent from the
      current page set are deleted. Foreign files, and files with no
      readable `generator:` stamp at all, are never touched - pruning only
      ever removes pages this generator is sure it owns. This half was
      already fail-closed (`== GENERATOR_NAME`, not `!=`) before this pass;
      it is unchanged here.
    """
    root = out_dir.resolve()
    root.mkdir(parents=True, exist_ok=True)

    resolved: dict[str, Path] = {}
    for rel in pages:
        path = (root / rel).resolve()
        if root not in (path, *path.parents):
            raise ValueError(f"page path escapes output dir: {rel}")
        if path.exists():
            # Deliberately not `_read_text_best_effort`: that helper feeds
            # the corpus-walk skip counter (`skipped_file_count`), and an
            # unreadable OUTPUT page is a different signal than a corpus
            # artifact - the two must not be conflated in one count.
            try:
                existing_text = path.read_text(encoding="utf-8")
            except OSError as exc:
                raise SystemExit(
                    f"refusing to overwrite {path}: could not read it to verify "
                    f"ownership ({exc}). Move the file aside or point --out at a "
                    "different directory."
                ) from exc
            owner = _frontmatter_generator(existing_text)
            if owner != GENERATOR_NAME:
                reason = (
                    f"generated by '{owner}'"
                    if owner
                    else "not stamped by any generator (missing, empty, or malformed frontmatter)"
                )
                raise SystemExit(
                    f"refusing to overwrite {path}: it is {reason}, not {GENERATOR_NAME}. "
                    "Move the file aside, or point --out at a directory not shared with "
                    "another generator's pages or hand-authored notes."
                )
        resolved[rel] = path

    for rel, path in resolved.items():
        path.write_text(pages[rel], encoding="utf-8")

    current_names = set(pages)
    for existing_path in sorted(root.glob("*.md")):
        if existing_path.name in current_names:
            continue
        try:
            text = existing_path.read_text(encoding="utf-8")
        except OSError:
            continue
        if _frontmatter_generator(text) == GENERATOR_NAME:
            existing_path.unlink()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate top-N stable-concept wiki pages from a video-intel corpus (issue #148)."
    )
    parser.add_argument("--corpus", type=Path, required=True, help="Path to the corpus (output_dir), read-only")
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output folder for the generated pages (default: <corpus>/_wiki/concept-pages)",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=DEFAULT_TOP_N,
        help=f"Number of stable concepts to render, must be >= 1 (default {DEFAULT_TOP_N})",
    )
    args = parser.parse_args()

    if args.top < 1:
        parser.error(f"--top must be >= 1 (got {args.top})")

    corpus = args.corpus.resolve()
    if not corpus.is_dir():
        sys.exit(f"corpus not found: {corpus}")
    out_dir = (args.out.resolve()) if args.out else (corpus / "_wiki" / "concept-pages")

    pages = build_pages(corpus, top_n=args.top)
    write_pages(pages, out_dir)
    concept_pages = len(pages) - 1  # everything but the MOC page
    skipped = skipped_file_count()
    print(
        f"wrote {len(pages)} pages to {out_dir} ({concept_pages} concept pages + MOC, "
        f"top {args.top} requested, {skipped} corpus files skipped as unreadable/unparseable)"
    )


if __name__ == "__main__":
    main()
