#!/usr/bin/env python3
"""Concept-page wiki generator (issue #148).

Emits an Obsidian-readable wiki slice - one page per top-N stable taxonomy
concept plus an index.md - into `<out>/_wiki/concepts` (or an explicit
`--out`). Companion to `scripts/wiki_atlas.py` (issue #105): same house
style (frontmatter stamps, wikilink discipline, TODO-PROSE slots), different
data source and a different generator, per the one-generator-not-a-framework
discipline from issue #95.

Read-only against the corpus: `taxonomy.json` (canonical labels/aliases) +
per-video `concepts.json` (concept membership) + `meta.json` (video
identity) + `mindmap.md` (timestamps for evidence links). No LLM calls, no
embeddings, no databases - plain Python over JSON/Markdown already on disk
(issue #148 guardrail 2). Pages are mechanical skeletons with TODO-PROSE
slots; an executing agent fills the prose in a later, separately gated step
(guardrail 3).

Standalone by design: this does NOT add a `video_intel.py` subcommand, so it
sidesteps the `CONFIG_BACKUP_COMMANDS` classification question entirely -
see the PR body for the full reasoning. It never touches `config.yaml` or
any file inside the corpus other than the read-only artifacts named above;
its only write surface is the `--out` directory.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from intel_graph import timestamped_url
from wiki_atlas import slugify

from video_intel import parse_time_to_seconds

GENERATOR_NAME = "wiki_concepts.py"
GENERATOR_VERSION = "1"

DEFAULT_TOP_N = 20
MIN_STABLE_CHANNELS = 3

CONCEPTS_SUFFIX = ".concepts.json"
META_SUFFIX = ".meta.json"
MINDMAP_SUFFIX = ".mindmap.md"

PROSE_TODO = "> [!todo] PROSE (agent)"
PROSE_INLINE = "(TODO-PROSE: one-line context)"

REGEN_NOTICE = (
    "Regenerated by rerunning the generator. Hand-edits outside the "
    "`> [!todo] PROSE` blocks are NOT preserved across a re-run."
)


# ---------------------------------------------------------------------------
# Domain model
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class VideoRecord:
    """One corpus video, identified the way the writer identified it on disk."""

    channel: str
    video_id: str
    title: str
    published: str  # ISO date string, "" if unknown
    video_url: str
    prefix: str
    mindmap_path: Path | None


@dataclass(frozen=True)
class Mention:
    """One (concept, video) membership fact, from that video's concepts.json."""

    video: VideoRecord
    concept_id: str
    preferred_label: str
    as_mentioned: str
    branch: str


@dataclass(frozen=True)
class MindmapEntry:
    """One bullet line parsed out of a mindmap.md, with its first timestamp."""

    heading: str
    subheading: str
    text: str
    seconds: int | None


# ---------------------------------------------------------------------------
# Corpus walk - never rebuilds artifact paths from parts (PR #136 guardrail)
# ---------------------------------------------------------------------------


def _is_channel_dir(path: Path) -> bool:
    return path.is_dir() and not path.name.startswith((".", "_"))


def artifact_prefix(concepts_path: Path) -> str:
    """The on-disk prefix for a concepts.json file (e.g. '2026-01-29-title')."""
    return concepts_path.name[: -len(CONCEPTS_SUFFIX)]


def sibling_artifacts(concepts_path: Path) -> dict[str, Path]:
    """Map of suffix (e.g. '.meta.json') -> path, from files actually present
    beside this concepts.json on disk.

    The prefix comes from the concepts.json filename the corpus walk already
    found, never rebuilt from title/date parts - the exact failure PR #136
    fixed (a checker that re-derives a writer's path independently, and
    drifts from it).
    """
    prefix = artifact_prefix(concepts_path)
    out: dict[str, Path] = {}
    for sib in concepts_path.parent.glob(f"{prefix}.*"):
        out[sib.name[len(prefix) :]] = sib
    return out


def _read_json_best_effort(path: Path) -> dict | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def _read_text_best_effort(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return None


def collect_corpus_videos(corpus: Path) -> list[tuple[VideoRecord, list[dict]]]:
    """Walk `<corpus>/<channel>/*.concepts.json`; return (video, concept-dicts).

    Skips `.`- and `_`-prefixed directories, mirroring the corpus walker
    convention (`_wiki`, `_briefings`, `_reports`, `_config-backups` are
    output folders, never channels).
    """
    records: list[tuple[VideoRecord, list[dict]]] = []
    if not corpus.is_dir():
        return records
    for channel_dir in sorted(p for p in corpus.iterdir() if _is_channel_dir(p)):
        for cpath in sorted(channel_dir.glob(f"*{CONCEPTS_SUFFIX}")):
            cdata = _read_json_best_effort(cpath)
            if not cdata:
                continue
            concepts = cdata.get("concepts") or []
            if not concepts:
                continue
            sibs = sibling_artifacts(cpath)
            meta = _read_json_best_effort(sibs[META_SUFFIX]) if META_SUFFIX in sibs else None
            meta = meta or {}
            prefix = artifact_prefix(cpath)
            video_id = meta.get("video_id") or cdata.get("video_id") or prefix
            title = meta.get("title") or prefix
            published = meta.get("published") or ""
            video_url = meta.get("video_url") or (f"https://www.youtube.com/watch?v={video_id}" if video_id else "")
            video = VideoRecord(
                channel=channel_dir.name,
                video_id=video_id,
                title=title,
                published=published,
                video_url=video_url,
                prefix=prefix,
                mindmap_path=sibs.get(MINDMAP_SUFFIX),
            )
            records.append((video, concepts))
    return records


def load_taxonomy(corpus: Path) -> dict[str, dict]:
    """Best-effort read of taxonomy.json's concept table; {} if missing/corrupt."""
    data = _read_json_best_effort(corpus / "taxonomy.json")
    if not data:
        return {}
    concepts = data.get("concepts")
    return concepts if isinstance(concepts, dict) else {}


# ---------------------------------------------------------------------------
# Concept membership + stability selection
# ---------------------------------------------------------------------------


def build_mentions(records: list[tuple[VideoRecord, list[dict]]]) -> dict[str, list[Mention]]:
    """Join concept -> videos via each video's own concepts.json, deduping a
    concept that (rarely) appears twice in one video's concept list."""
    by_concept: dict[str, list[Mention]] = {}
    for video, concepts in records:
        seen_this_video: set[str] = set()
        for c in concepts:
            cid = c.get("concept_id")
            if not cid or cid in seen_this_video:
                continue
            seen_this_video.add(cid)
            by_concept.setdefault(cid, []).append(
                Mention(
                    video=video,
                    concept_id=cid,
                    preferred_label=c.get("preferred_label") or cid,
                    as_mentioned=c.get("as_mentioned") or "",
                    branch=c.get("branch") or "",
                )
            )
    return by_concept


def select_stable_concepts(
    mentions_by_concept: dict[str, list[Mention]],
    top_n: int = DEFAULT_TOP_N,
    min_channels: int = MIN_STABLE_CHANNELS,
) -> list[str]:
    """Rank concepts by distinct-video count; keep only ones seen across
    `>= min_channels` distinct channels (one creator's pet vocabulary must
    not claim a page even at high count). Deterministic tie-break on
    concept_id so a rerun with unchanged inputs orders identically.
    """
    scored: list[tuple[str, int]] = []
    for cid, mentions in mentions_by_concept.items():
        channels = {m.video.channel for m in mentions}
        if len(channels) < min_channels:
            continue
        video_count = len({m.video.video_id for m in mentions})
        scored.append((cid, video_count))
    scored.sort(key=lambda t: (-t[1], t[0]))
    return [cid for cid, _ in scored[:top_n]]


def build_co_occurrence(records: list[tuple[VideoRecord, list[dict]]], selected_ids: set[str]) -> dict[str, Counter]:
    """concept_id -> Counter(other_concept_id -> shared-video count), scoped
    to the selected concept set only - the "Related concepts" cross-link
    source. Restricting to selected_ids means every link this produces
    points at a page that exists in this run (zero dead wikilinks)."""
    co: dict[str, Counter] = {cid: Counter() for cid in selected_ids}
    for _video, concepts in records:
        ids_in_video = sorted({c.get("concept_id") for c in concepts if c.get("concept_id") in selected_ids})
        for a in ids_in_video:
            for b in ids_in_video:
                if a != b:
                    co[a][b] += 1
    return co


# ---------------------------------------------------------------------------
# Mindmap timestamp parsing (mechanical; matches the mindmap-from-transcript
# prompt's heading / subheading / timestamped-bullet shape - see
# prompts/mindmap-from-transcript.md)
# ---------------------------------------------------------------------------

_HEADING_RE = re.compile(r"^##\s+(.+)$")
_SUBHEADING_RE = re.compile(r"^\*\s+\*\*(.+?)\*\*\s*$")
_BULLET_TIME_RE = re.compile(r"\(([\d:,\s]+)\)\s*$")
_TIME_TOKEN_RE = re.compile(r"\d{1,2}(?::\d{2}){1,2}")


def parse_mindmap_timestamps(text: str) -> list[MindmapEntry]:
    """Parse `## heading` / `* **subheading**` / `  - bullet (M:SS)` rows into
    a flat list carrying each bullet's first timestamp (seconds), or None
    when a bullet carries no parseable timestamp. Not a markdown library -
    the corpus's mindmap shape is stable and prompt-defined."""
    entries: list[MindmapEntry] = []
    heading = ""
    subheading = ""
    for raw_line in text.splitlines():
        line = raw_line.strip()
        h = _HEADING_RE.match(line)
        if h:
            heading = h.group(1).strip()
            subheading = ""
            continue
        s = _SUBHEADING_RE.match(line)
        if s:
            subheading = s.group(1).strip()
            continue
        if not line.startswith("-"):
            continue
        seconds = None
        m = _BULLET_TIME_RE.search(line)
        if m:
            tokens = _TIME_TOKEN_RE.findall(m.group(1))
            if tokens:
                try:
                    seconds = parse_time_to_seconds(tokens[0])
                except ValueError:
                    seconds = None
        bullet_text = _BULLET_TIME_RE.sub("", line).lstrip("-").strip()
        entries.append(MindmapEntry(heading=heading, subheading=subheading, text=bullet_text, seconds=seconds))
    return entries


def find_timestamp(entries: list[MindmapEntry], branch: str, as_mentioned: str) -> int | None:
    """Deterministic, mechanical lookup for the timestamp behind one concept
    mention: first try a subheading match on `branch`, then a heading match,
    then a substring match of `as_mentioned` inside any bullet's text. None
    when nothing matches - callers must not fabricate a timestamp; an
    un-anchored citation renders without `&t=` rather than with a wrong one.
    """
    branch_norm = branch.strip().lower()
    as_mentioned_norm = as_mentioned.strip().lower()
    if branch_norm:
        for e in entries:
            if e.seconds is not None and e.subheading.strip().lower() == branch_norm:
                return e.seconds
        for e in entries:
            if e.seconds is not None and e.heading.strip().lower() == branch_norm:
                return e.seconds
    if as_mentioned_norm:
        for e in entries:
            if e.seconds is not None and as_mentioned_norm in e.text.strip().lower():
                return e.seconds
    return None


def mention_link(m: Mention, entries_cache: dict[Path, list[MindmapEntry]]) -> str:
    """URL for one mention: `&t=<seconds>` when a timestamp can be located in
    the video's mindmap, else the plain video URL - never a fabricated time."""
    seconds = None
    if m.video.mindmap_path is not None:
        entries = entries_cache.get(m.video.mindmap_path)
        if entries is None:
            text = _read_text_best_effort(m.video.mindmap_path)
            entries = parse_mindmap_timestamps(text) if text is not None else []
            entries_cache[m.video.mindmap_path] = entries
        seconds = find_timestamp(entries, m.branch, m.as_mentioned)
    return timestamped_url(m.video.video_url, seconds)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _concept_page(
    concept_id: str,
    mentions: list[Mention],
    taxonomy: dict[str, dict],
    co_occurrence: dict[str, Counter],
    slug_for: dict[str, str],
    entries_cache: dict[Path, list[MindmapEntry]],
    corpus: Path,
) -> str:
    tax_entry = taxonomy.get(concept_id, {})
    label = tax_entry.get("preferred_label") or mentions[0].preferred_label
    aliases = tax_entry.get("aliases") or []
    domain = tax_entry.get("domain") or ""
    video_ids = sorted({m.video.video_id for m in mentions})
    channels = sorted({m.video.channel for m in mentions})

    lines = [
        "---",
        "type: concept",
        f"concept_id: {concept_id}",
        f"generator: {GENERATOR_NAME}",
        f"generator_version: {GENERATOR_VERSION!r}",
        f"generated_from: {corpus}",
        f"videos: {len(video_ids)}",
        f"channels: {len(channels)}",
        "---",
        "",
        f"# {label}",
        "",
        f"> {REGEN_NOTICE}",
        "",
        PROSE_TODO,
        f"> Write 2-3 paragraphs on {label}: what it is, why it recurs across "
        "creators, and a judgment on where it is heading.",
        "",
    ]
    if domain:
        lines += [f"Domain: `{domain}`", ""]
    if aliases:
        lines += ["## Aliases", ""]
        lines += [f"- {a}" for a in sorted(aliases)]
        lines.append("")

    lines += [f"## Member videos ({len(video_ids)} across {len(channels)} channels)", ""]
    by_channel: dict[str, list[Mention]] = {}
    for m in mentions:
        by_channel.setdefault(m.video.channel, []).append(m)
    for channel in sorted(by_channel):
        lines += [f"### {channel}", "", "| Date | Video | As mentioned |", "|---|---|---|"]
        rows = sorted(by_channel[channel], key=lambda m: (m.video.published, m.video.title, m.video.video_id))
        seen_videos: set[str] = set()
        for m in rows:
            if m.video.video_id in seen_videos:
                continue
            seen_videos.add(m.video.video_id)
            link = mention_link(m, entries_cache)
            date = m.video.published or "(date unknown)"
            claim = m.as_mentioned or m.branch or "-"
            lines.append(f"| {date} | [{m.video.title}]({link}) | {claim} |")
        lines.append("")

    related = co_occurrence.get(concept_id, Counter())
    related_ranked = sorted(
        ((cid, n) for cid, n in related.items() if cid in slug_for and cid != concept_id),
        key=lambda t: (-t[1], t[0]),
    )
    if related_ranked:
        lines += ["## Related concepts", ""]
        for cid, n in related_ranked:
            other_label = taxonomy.get(cid, {}).get("preferred_label") or cid
            plural = "s" if n != 1 else ""
            lines.append(f"- [[{slug_for[cid]}]] ({other_label}) - shares {n} video{plural} - {PROSE_INLINE}")
        lines.append("")

    return "\n".join(lines)


def _index(
    selected_ids: list[str],
    mentions_by_concept: dict[str, list[Mention]],
    taxonomy: dict[str, dict],
    slug_for: dict[str, str],
    corpus: Path,
) -> str:
    lines = [
        "---",
        "type: index",
        f"generator: {GENERATOR_NAME}",
        f"generator_version: {GENERATOR_VERSION!r}",
        f"generated_from: {corpus}",
        f"pages: {len(selected_ids)}",
        "---",
        "",
        "# Concept Atlas",
        "",
        f"> {REGEN_NOTICE}",
        "",
        PROSE_TODO,
        "> Write the MOC intro: what this atlas is, how to wander it, one line of context per link below.",
        "",
        f"## Top {len(selected_ids)} stable concepts",
        "",
    ]
    for i, cid in enumerate(selected_ids, start=1):
        mentions = mentions_by_concept[cid]
        video_ids = {m.video.video_id for m in mentions}
        channels = {m.video.channel for m in mentions}
        label = taxonomy.get(cid, {}).get("preferred_label") or mentions[0].preferred_label
        lines.append(
            f"{i}. [[{slug_for[cid]}]] - {label} - {len(video_ids)} videos across "
            f"{len(channels)} channels - {PROSE_INLINE}"
        )
    lines.append("")
    return "\n".join(lines)


def _assign_slugs(selected_ids: list[str]) -> dict[str, str]:
    """Deterministic slug per concept_id, disambiguating collisions with a
    numeric suffix (mirrors wiki_atlas's collision handling) so one page
    never silently overwrites another."""
    slug_for: dict[str, str] = {}
    used: set[str] = set()
    for cid in selected_ids:
        base = slug = slugify(cid)
        n = 2
        while slug in used:
            slug = f"{base}-{n}"
            n += 1
        used.add(slug)
        slug_for[cid] = slug
    return slug_for


def build_pages(
    corpus: Path,
    top_n: int = DEFAULT_TOP_N,
    min_channels: int = MIN_STABLE_CHANNELS,
) -> dict[str, str]:
    """Pure(ish) top-level renderer: corpus directory -> {relative path: markdown}.

    The only filesystem interaction is reading; nothing is written here.
    """
    records = collect_corpus_videos(corpus)
    mentions_by_concept = build_mentions(records)
    selected_ids = select_stable_concepts(mentions_by_concept, top_n=top_n, min_channels=min_channels)
    taxonomy = load_taxonomy(corpus)
    co_occurrence = build_co_occurrence(records, set(selected_ids))
    slug_for = _assign_slugs(selected_ids)
    entries_cache: dict[Path, list[MindmapEntry]] = {}

    pages: dict[str, str] = {}
    for cid in selected_ids:
        pages[f"{slug_for[cid]}.md"] = _concept_page(
            cid, mentions_by_concept[cid], taxonomy, co_occurrence, slug_for, entries_cache, corpus
        )
    pages["index.md"] = _index(selected_ids, mentions_by_concept, taxonomy, slug_for, corpus)
    return pages


def write_pages(pages: dict[str, str], out_dir: Path) -> None:
    """Write every page under out_dir; refuses to write anywhere else."""
    root = out_dir.resolve()
    root.mkdir(parents=True, exist_ok=True)
    for rel, content in pages.items():
        path = (root / rel).resolve()
        if root not in (path, *path.parents):
            raise ValueError(f"page path escapes output dir: {rel}")
        path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate top-N stable-concept wiki pages from a video-intel corpus (issue #148)."
    )
    parser.add_argument("--corpus", type=Path, required=True, help="Path to the corpus (output_dir), read-only")
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output folder for the generated pages (default: <corpus>/_wiki/concepts)",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=DEFAULT_TOP_N,
        help=f"Number of stable concepts to render (default {DEFAULT_TOP_N})",
    )
    args = parser.parse_args()

    corpus = args.corpus.resolve()
    if not corpus.is_dir():
        sys.exit(f"corpus not found: {corpus}")
    out_dir = (args.out.resolve()) if args.out else (corpus / "_wiki" / "concepts")

    pages = build_pages(corpus, top_n=args.top)
    write_pages(pages, out_dir)
    concept_pages = len(pages) - 1  # everything but index.md
    print(f"wrote {len(pages)} pages to {out_dir} ({concept_pages} concept pages + index, top {args.top} requested)")


if __name__ == "__main__":
    main()
